### PR TITLE
Non-breaking changes, added an optional length at which to call off t…

### PR DESCRIPTION
**Pull request by bcriger**
…he search, and replaced the single target vertex with a callback predicate that determines whether a vertex can be considered a target.

### CODE REVIEW

**Comment by scheinerman** [comment]
Thanks @bcriger . This is interesting. I have a question and a request.

First, can you explain more how `stop_length` works. I'm inferring this to mean that we don't consider longer paths. But then, does setting this to `0` allow an unrestricted search?

Second, would you please also modify the `README` to document this?

**Comment by scheinerman** [comment]
Also: Can you propose something to be added to `runtests` to test this?

**Comment by scheinerman** [comment]
Thanks. I merged. I'll check it out, and then release the new version.

**Comment by scheinerman** [comment]
@bcriger One more question: The `cutoff_depth` parameter is set to `0` to remove all restrictions. Is that right?

**Comment by bcriger** [comment]
That's right. I would have set it to `Inf` for clarity, but integer types don't have an `Inf`. I was thinking about setting it to `-1` as a shorthand for an unused value, but I couldn't get it working easily and cleanly, so I stuck with 0, and made it the default so I don't break pre-existing code that uses `ImplicitGraphs`.

**Comment by scheinerman** [comment]
Great. I'll document that.

**Comment by scheinerman** [comment]
@bcriger The version has migrated. Thanks again for your contribution.

**Pull request merged**
